import type { SupportedLanguage } from "@3d-budget/shared";
import type { Prisma } from "@prisma/client";
import PDFDocument from "pdfkit";
import { prisma } from "../config/prisma";
import { AppError } from "../middlewares/error-handler";

const quotePdfInclude = {
  company: {
    include: {
      user: { select: { email: true, language: true } },
    },
  },
  formula: { select: { name: true } },
  printItems: {
    orderBy: { createdAt: "asc" as const },
    include: {
      machine: { select: { name: true } },
      material: { select: { brand: true, color: true, type: true } },
    },
  },
} satisfies Prisma.QuoteInclude;

type QuotePdfRecord = Prisma.QuoteGetPayload<{ include: typeof quotePdfInclude }>;

interface QuotePdfResult {
  buffer: Buffer;
  filename: string;
}

const colors = {
  primary: "#6366F1",
  primaryDark: "#4338CA",
  ink: "#111827",
  muted: "#6B7280",
  soft: "#F8FAFC",
  line: "#E5E7EB",
  white: "#FFFFFF",
};

// Display-only formatting swap (no real currency conversion) — see
// Contextos/Decisoes.md, 2026-08-17.
const pdfStrings = {
  "pt-BR": {
    docTitlePrefix: "Orcamento",
    docSubjectPrefix: "Orcamento para",
    contactLabel: "Contato:",
    taxIdUnknown: "CNPJ/CPF: nao informado",
    quoteHeading: "ORCAMENTO",
    statusLabel: "Status:",
    clientLabel: "Cliente",
    issuedLabel: "Emitido em",
    validUntilLabel: "Validade",
    sectionItems: "Mesas de impressao",
    columns: {
      piece: "Peca",
      qty: "Qtd",
      material: "Material",
      machine: "Maquina",
      weightTime: "Peso/Tempo",
      value: "Valor",
    },
    subtotal: "Subtotal",
    discounts: "Descontos",
    total: "Valor total",
    formulaApplied: "Formula aplicada:",
    defaultFormulaName: "Formula Padrao do Sistema",
    totalWeight: (value: string) => `Peso total: ${value} g`,
    totalTime: (value: string) => `Tempo total: ${value} h`,
    termsHeading: "Termos e observacoes",
    terms: [
      "Garantia limitada a defeitos de fabricacao do servico de impressao.",
      "Prazo de entrega estimado sera confirmado apos aprovacao e disponibilidade de producao.",
      "Alteracoes de arquivo, escala, material ou acabamento podem exigir novo orcamento.",
    ],
    validUntilNote: (date: string) => `Orcamento valido ate ${date}.`,
    footer: (companyName: string) =>
      `${companyName} - Documento gerado pelo 3D Budget SaaS`,
    filenamePrefix: "Orcamento",
    filenameFallback: "Cliente",
    currency: { locale: "pt-BR", currency: "BRL" },
    dateLocale: "pt-BR",
  },
  en: {
    docTitlePrefix: "Quote",
    docSubjectPrefix: "Quote for",
    contactLabel: "Contact:",
    taxIdUnknown: "Tax ID: not provided",
    quoteHeading: "QUOTE",
    statusLabel: "Status:",
    clientLabel: "Customer",
    issuedLabel: "Issued on",
    validUntilLabel: "Valid until",
    sectionItems: "Print items",
    columns: {
      piece: "Item",
      qty: "Qty",
      material: "Material",
      machine: "Machine",
      weightTime: "Weight/Time",
      value: "Price",
    },
    subtotal: "Subtotal",
    discounts: "Discounts",
    total: "Total amount",
    formulaApplied: "Formula applied:",
    defaultFormulaName: "System Default Formula",
    totalWeight: (value: string) => `Total weight: ${value} g`,
    totalTime: (value: string) => `Total time: ${value} h`,
    termsHeading: "Terms and notes",
    terms: [
      "Warranty limited to manufacturing defects in the printing service.",
      "Estimated delivery time will be confirmed after approval and production availability.",
      "File, scale, material or finishing changes may require a new quote.",
    ],
    validUntilNote: (date: string) => `Quote valid until ${date}.`,
    footer: (companyName: string) =>
      `${companyName} - Document generated by 3D Budget SaaS`,
    filenamePrefix: "Quote",
    filenameFallback: "Customer",
    currency: { locale: "en-US", currency: "USD" },
    dateLocale: "en-US",
  },
} as const satisfies Record<SupportedLanguage, unknown>;

type PdfStrings = (typeof pdfStrings)[SupportedLanguage];

const decimalToNumber = (value: Prisma.Decimal): number =>
  Number(value.toString());

const formatMoney = (
  value: Prisma.Decimal | number,
  strings: PdfStrings,
): string =>
  new Intl.NumberFormat(strings.currency.locale, {
    style: "currency",
    currency: strings.currency.currency,
  }).format(typeof value === "number" ? value : decimalToNumber(value));

const formatDate = (value: Date, strings: PdfStrings): string =>
  new Intl.DateTimeFormat(strings.dateLocale, {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    timeZone: "America/Sao_Paulo",
  }).format(value);

const sanitizeFilenamePart = (value: string, fallback: string): string => {
  const COMBINING_DIACRITICS = new RegExp("[̀-ͯ]", "g");
  const normalized = value
    .normalize("NFD")
    .replace(COMBINING_DIACRITICS, "")
    .replace(/[^a-zA-Z0-9_-]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");

  return normalized.slice(0, 48) || fallback;
};

const buildFilename = (quote: QuotePdfRecord, strings: PdfStrings): string => {
  const shortId = quote.id.slice(0, 8);
  const customer = sanitizeFilenamePart(quote.customerName, strings.filenameFallback);

  return `${strings.filenamePrefix}_${shortId}_${customer}.pdf`;
};

const collectDocument = (doc: PDFKit.PDFDocument): Promise<Buffer> => {
  const chunks: Buffer[] = [];

  doc.on("data", (chunk: Buffer | Uint8Array) => {
    chunks.push(Buffer.from(chunk));
  });

  return new Promise((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
};

const getLogoBuffer = (logoUrl: string | null): Buffer | null => {
  if (!logoUrl) {
    return null;
  }

  const dataUri = /^data:image\/(?:png|jpe?g);base64,(.+)$/i.exec(logoUrl);

  if (!dataUri) {
    return null;
  }

  try {
    return Buffer.from(dataUri[1], "base64");
  } catch {
    return null;
  }
};

const drawLogo = (
  doc: PDFKit.PDFDocument,
  quote: QuotePdfRecord,
  x: number,
  y: number,
): void => {
  const logoBuffer = getLogoBuffer(quote.company.logoUrl);

  if (logoBuffer) {
    try {
      doc.image(logoBuffer, x, y, { fit: [58, 58] });
      return;
    } catch {
      // Falls back to monogram when an uploaded image is not readable.
    }
  }

  const initials = quote.company.name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase())
    .join("");

  doc
    .roundedRect(x, y, 58, 58, 12)
    .fill(colors.primary)
    .fillColor(colors.white)
    .font("Helvetica-Bold")
    .fontSize(18)
    .text(initials || "3D", x, y + 20, {
      width: 58,
      align: "center",
    });
};

const drawKeyValue = (
  doc: PDFKit.PDFDocument,
  label: string,
  value: string,
  x: number,
  y: number,
  width: number,
): void => {
  doc
    .fillColor(colors.muted)
    .font("Helvetica")
    .fontSize(8)
    .text(label.toUpperCase(), x, y, { width });
  doc
    .fillColor(colors.ink)
    .font("Helvetica-Bold")
    .fontSize(10)
    .text(value, x, y + 12, { width });
};

const drawHeader = (
  doc: PDFKit.PDFDocument,
  quote: QuotePdfRecord,
  strings: PdfStrings,
): void => {
  const margin = 48;
  const rightX = 365;

  drawLogo(doc, quote, margin, margin);

  doc
    .fillColor(colors.ink)
    .font("Helvetica-Bold")
    .fontSize(18)
    .text(quote.company.name, margin + 74, margin + 2, { width: 260 });
  doc
    .fillColor(colors.muted)
    .font("Helvetica")
    .fontSize(9)
    .text(`${strings.contactLabel} ${quote.company.user.email}`, margin + 74, margin + 28, {
      width: 260,
    })
    .text(strings.taxIdUnknown, margin + 74, margin + 42, {
      width: 260,
    });

  doc
    .font("Helvetica-Bold")
    .fontSize(22)
    .fillColor(colors.primaryDark)
    .text(strings.quoteHeading, rightX, margin, { width: 180, align: "right" });
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(colors.muted)
    .text(`#${quote.id.slice(0, 8).toUpperCase()}`, rightX, margin + 28, {
      width: 180,
      align: "right",
    })
    .text(`${strings.statusLabel} ${quote.status}`, rightX, margin + 42, {
      width: 180,
      align: "right",
    });

  doc
    .moveTo(margin, 128)
    .lineTo(doc.page.width - margin, 128)
    .lineWidth(2)
    .strokeColor(colors.primary)
    .stroke();
};

const drawCustomerBlock = (
  doc: PDFKit.PDFDocument,
  quote: QuotePdfRecord,
  y: number,
  strings: PdfStrings,
): number => {
  const margin = 48;
  const width = doc.page.width - margin * 2;

  doc.roundedRect(margin, y, width, 72, 10).fill(colors.soft);
  drawKeyValue(doc, strings.clientLabel, quote.customerName, margin + 18, y + 16, 210);
  drawKeyValue(
    doc,
    strings.issuedLabel,
    formatDate(quote.createdAt, strings),
    margin + 248,
    y + 16,
    100,
  );
  drawKeyValue(
    doc,
    strings.validUntilLabel,
    formatDate(quote.validUntil, strings),
    margin + 365,
    y + 16,
    100,
  );

  return y + 98;
};

const buildTableColumns = (strings: PdfStrings) => [
  { label: strings.columns.piece, width: 132 },
  { label: strings.columns.qty, width: 38 },
  { label: strings.columns.material, width: 105 },
  { label: strings.columns.machine, width: 88 },
  { label: strings.columns.weightTime, width: 62 },
  { label: strings.columns.value, width: 74 },
];

const drawItemsHeader = (
  doc: PDFKit.PDFDocument,
  y: number,
  tableColumns: ReturnType<typeof buildTableColumns>,
): number => {
  const margin = 48;
  let x = margin;

  doc.roundedRect(margin, y, doc.page.width - margin * 2, 26, 7).fill(colors.primary);

  for (const column of tableColumns) {
    doc
      .fillColor(colors.white)
      .font("Helvetica-Bold")
      .fontSize(8)
      .text(column.label.toUpperCase(), x + 8, y + 9, {
        width: column.width - 12,
      });
    x += column.width;
  }

  return y + 30;
};

const ensurePageSpace = (
  doc: PDFKit.PDFDocument,
  y: number,
  neededHeight: number,
  tableColumns?: ReturnType<typeof buildTableColumns>,
): number => {
  const bottom = doc.page.height - 70;

  if (y + neededHeight <= bottom) {
    return y;
  }

  doc.addPage();
  return tableColumns ? drawItemsHeader(doc, 48, tableColumns) : 48;
};

const drawItemsTable = (
  doc: PDFKit.PDFDocument,
  quote: QuotePdfRecord,
  y: number,
  strings: PdfStrings,
): number => {
  const tableColumns = buildTableColumns(strings);
  let currentY = drawItemsHeader(doc, y, tableColumns);
  const margin = 48;

  for (const [index, item] of quote.printItems.entries()) {
    const rowHeight = Math.max(
      46,
      doc.heightOfString(item.modelName, {
        width: tableColumns[0].width - 14,
      }) + 22,
    );

    currentY = ensurePageSpace(doc, currentY, rowHeight, tableColumns);

    if (index % 2 === 0) {
      doc
        .rect(margin, currentY - 3, doc.page.width - margin * 2, rowHeight)
        .fill("#FBFCFF");
    }

    let x = margin;
    const material = `${item.material.brand} ${item.material.color}`;
    const metrics = `${decimalToNumber(item.materialWeightGrams).toFixed(0)} g\n${decimalToNumber(
      item.estimatedPrintTimeHours,
    ).toFixed(2)} h`;
    const values = [
      item.modelName,
      "1",
      material,
      item.machine.name,
      metrics,
      formatMoney(item.finalPrice, strings),
    ];

    values.forEach((value, columnIndex) => {
      const column = tableColumns[columnIndex];
      doc
        .fillColor(columnIndex === 5 ? colors.ink : colors.muted)
        .font(columnIndex === 0 || columnIndex === 5 ? "Helvetica-Bold" : "Helvetica")
        .fontSize(columnIndex === 5 ? 9 : 8)
        .text(value, x + 8, currentY + 10, {
          width: column.width - 12,
          align: columnIndex === 5 ? "right" : "left",
        });
      x += column.width;
    });

    doc
      .moveTo(margin, currentY + rowHeight - 3)
      .lineTo(doc.page.width - margin, currentY + rowHeight - 3)
      .lineWidth(0.5)
      .strokeColor(colors.line)
      .stroke();

    currentY += rowHeight;
  }

  return currentY + 18;
};

const drawFinancialSummary = (
  doc: PDFKit.PDFDocument,
  quote: QuotePdfRecord,
  y: number,
  strings: PdfStrings,
): number => {
  const margin = 48;
  const boxWidth = 220;
  const x = doc.page.width - margin - boxWidth;
  const subtotal = quote.totalAmount;

  const currentY = ensurePageSpace(doc, y, 126);
  doc.roundedRect(x, currentY, boxWidth, 126, 10).fill(colors.soft);

  const rows = [
    [strings.subtotal, formatMoney(subtotal, strings)],
    [strings.discounts, formatMoney(0, strings)],
    [strings.total, formatMoney(subtotal, strings)],
  ] as const;

  rows.forEach(([label, value], index) => {
    const rowY = currentY + 18 + index * 31;
    doc
      .fillColor(index === 2 ? colors.primaryDark : colors.muted)
      .font(index === 2 ? "Helvetica-Bold" : "Helvetica")
      .fontSize(index === 2 ? 12 : 9)
      .text(label, x + 16, rowY, { width: 100 });
    doc
      .fillColor(index === 2 ? colors.primaryDark : colors.ink)
      .font("Helvetica-Bold")
      .fontSize(index === 2 ? 15 : 10)
      .text(value, x + 100, rowY - (index === 2 ? 2 : 0), {
        width: 104,
        align: "right",
      });
  });

  doc
    .fillColor(colors.muted)
    .font("Helvetica")
    .fontSize(8)
    .text(
      `${strings.formulaApplied} ${quote.formula?.name ?? strings.defaultFormulaName}`,
      margin,
      currentY + 12,
      { width: x - margin - 18 },
    )
    .text(
      strings.totalWeight(decimalToNumber(quote.totalWeightGrams).toFixed(2)),
      margin,
      currentY + 30,
      { width: x - margin - 18 },
    )
    .text(
      strings.totalTime(decimalToNumber(quote.totalPrintHours).toFixed(2)),
      margin,
      currentY + 46,
      { width: x - margin - 18 },
    );

  return currentY + 148;
};

const drawTerms = (
  doc: PDFKit.PDFDocument,
  quote: QuotePdfRecord,
  y: number,
  strings: PdfStrings,
): void => {
  const margin = 48;
  const currentY = ensurePageSpace(doc, y, 120);

  doc
    .fillColor(colors.ink)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text(strings.termsHeading, margin, currentY);
  doc
    .fillColor(colors.muted)
    .font("Helvetica")
    .fontSize(8.5)
    .text(
      [...strings.terms, strings.validUntilNote(formatDate(quote.validUntil, strings))].join(
        "\n",
      ),
      margin,
      currentY + 18,
      { width: doc.page.width - margin * 2, lineGap: 4 },
    );

  doc
    .moveTo(margin, doc.page.height - 46)
    .lineTo(doc.page.width - margin, doc.page.height - 46)
    .lineWidth(0.5)
    .strokeColor(colors.line)
    .stroke();
  doc
    .fillColor(colors.muted)
    .fontSize(7)
    .text(strings.footer(quote.company.name), margin, doc.page.height - 34, {
      width: doc.page.width - margin * 2,
      align: "center",
    });
};

const renderQuotePdf = (
  doc: PDFKit.PDFDocument,
  quote: QuotePdfRecord,
  strings: PdfStrings,
): void => {
  drawHeader(doc, quote, strings);
  let y = drawCustomerBlock(doc, quote, 150, strings);

  doc
    .fillColor(colors.ink)
    .font("Helvetica-Bold")
    .fontSize(13)
    .text(strings.sectionItems, 48, y);

  y = drawItemsTable(doc, quote, y + 22, strings);
  y = drawFinancialSummary(doc, quote, y, strings);
  drawTerms(doc, quote, y, strings);
};

export class QuotePdfService {
  async generate(companyId: string, quoteId: string): Promise<QuotePdfResult> {
    const quote = await prisma.quote.findFirst({
      where: { id: quoteId, companyId },
      include: quotePdfInclude,
    });

    if (!quote) {
      // "Access denied." on purpose — see Contextos/Conhecimento.md.
      throw new AppError("Access denied.", 403, "QUOTE_FORBIDDEN");
    }

    const language = quote.company.user.language as SupportedLanguage;
    const strings = pdfStrings[language];

    const doc = new PDFDocument({
      size: "A4",
      margin: 48,
      bufferPages: true,
      info: {
        Title: `${strings.docTitlePrefix} ${quote.id.slice(0, 8).toUpperCase()}`,
        Author: quote.company.name,
        Subject: `${strings.docSubjectPrefix} ${quote.customerName}`,
        Creator: "3D Budget SaaS",
      },
    });
    const pdfBuffer = collectDocument(doc);

    renderQuotePdf(doc, quote, strings);
    doc.end();

    return {
      buffer: await pdfBuffer,
      filename: buildFilename(quote, strings),
    };
  }
}

export const quotePdfService = new QuotePdfService();
